name: Deploy SubnetSuite (Self-Hosted Runner)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish .NET app
        shell: powershell
        run: |
          cd C:\Users\Administrator\Capstone
          git pull origin main

          # Stop existing app
          Get-Process dotnet -ErrorAction SilentlyContinue | Where-Object { $_.Path -like "*SubnetSuite*" } | Stop-Process -Force

          # Publish to folder
          dotnet publish .\SubnetCalc\SubnetCalc.csproj -c Release -o C:\Published\SubnetSuite --nologo

          # Start in background
          Start-Process -FilePath "dotnet" -ArgumentList "C:\Published\SubnetSuite\SubnetCalc.dll", "--urls=http://localhost:5000"
