name: Deploy SubnetSuite (Direct .NET Publish)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # This targets your self-hosted runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish .NET app
        shell: powershell
        run: |
          cd C:\Users\Administrator\Capstone
          git pull origin main
          dotnet publish .\SubnetCalc\SubnetCalc.csproj -c Release -o C:\Published\SubnetSuite --nologo
          Stop-Process -Name "dotnet" -Force -ErrorAction SilentlyContinue
          Start-Process "dotnet" "C:\Published\SubnetSuite\SubnetCalc.dll"
