name: Deploy to SubnetSuite Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        shell: pwsh
        run: |
          cd C:\Users\Administrator\Capstone
          docker stop subnetsuite; if ($?) { Write-Host "Stopped container" } else { Write-Host "Container not running or doesn't exist" }
          docker rm subnetsuite; if ($?) { Write-Host "Removed container" } else { Write-Host "Container not found" }
          docker build -t subnetsuite .
          docker run -d --name subnetsuite -p 5000:80 subnetsuite

