name: Deploy to SubnetSuite Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          cd C:\Users\Administrator\Capstone
          git pull origin main
          docker stop subnetsuite || true
          docker rm subnetsuite || true
          docker build -t subnetsuite .
          docker run -d --name subnetsuite -p 5000:80 subnetsuite
